### ISSUE TITLE
[Question] Is there a way to manually globally tone down the emissivity?

### ISSUE THREAD

**Issue by TheAyes** [osfanbuff63/emissive-ores#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Requested Feature

Hi! I really like your resource pack and I'm using a shader. Apparently The glow that comes from the ores is a bit overkill for me and while I could just turn it down in the shader it would mean that anything else is affected aswell.
Since I'm happy with how it looks elsewhere, I'm asking if there's a way to tune the glowyness a bit down so it doesn't shine as bright :)
I sadly am no expert in the resource-pack scene so I hope you might be able to help me out ^-^

**Comment by osfanbuff63** [comment]
Sorry for the delay in response!

Unfortunately there isn't an easy way to turn down the brightness - what you would have to do is edit all the PNG files with `_e` at the end of their file name (e.g. `diamond_ore_e.png`) and tone down the brightness for all of those files. I could try and do that myself, but it might be a few days.

**Comment by TheAyes** [comment]
Oh no worries. I was hoping for a slider or a config file.  I understand if that's not possible :) You don't have to redo the images just for me. That would be out of scope for my question. 😅
Thank you anyways c: I'll just reduce the bloom in my shader then. That should be the easier way to go.
